### ISSUE TITLE
Twins

### ISSUE THREAD

**Issue by Tchuanm** [xiaohu2015/pvt_detectron2#1]
hi,  I notice the references include   4 papers, are they all include in this repo? especially Twins.

**Comment by xiaohu2015** [comment]
@Tchuanm Yes, PVT, CPVT, Twins-SVT-S are all included.

**Comment by Tchuanm** [comment]
Thank you very much. ~

**Comment by Tchuanm** [comment]
> @Tchuanm Yes, PVT, CPVT, Twins-SVT-S are all included.

I will try to use it. Thanks for your work~
