### ISSUE TITLE
Converted pretrained model

### ISSUE THREAD

**Issue by trqminh** [xiaohu2015/pvt_detectron2#2]
Hi @xiaohu2015,
Thank you for your consideration.
I have a problem when using your pre-trained PVT model (PVT-Small) as a backbone for my training. Indeed, I also converted the model to detectron2 by your  `convert_to_d2.py` (I saved the model as a .pth file). However, there is an error:
```
/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 292, in _convert_ndarray_to_tensor
    "Unsupported type found in checkpoint! {}: {}".format(k, type(v))
ValueError: Unsupported type found in checkpoint! backbone.bottom_up.model: <class 'collections.OrderedDict'>

```

**Comment by xiaohu2015** [comment]
I test the code, this is no problem:
1. download the pretrained weight file from https://github.com/whai362/PVT/releases/download/v2/pvt_small.pth
   ref: https://github.com/whai362/PVT/tree/v2/classification
2.
```
python convert_to_d2.py --source_model v2/pvt_small.pth --output_model=pvt_small_v2_d2.pth
```

**Comment by trqminh** [comment]
Thank you for your response.
I think I resolved my problem, I can load the weight and run the pipeline with PVT as the backbone. 
Actually just used the model key in the state dict and it still works cause I notice that the prefix `backbone.bottom_up` is already in the model.
```
    source_weights = torch.load(args.source_model)["model"]
    converted_weights = deepcopy(source_weights)

    #import pdb;pdb.set_trace()
    #converted_weights = {}
    #keys = list(source_weights.keys())
    #prefix = 'backbone.bottom_up.'
    #for key in keys:
    #    print(key)
    #    converted_weights[prefix+key] = source_weights[key]

    torch.save(converted_weights, args.output_model, _use_new_zipfile_serialization=False)
```
