### ISSUE TITLE
Pretrained model for pvt medium or pvt large

### ISSUE THREAD

**Issue by trqminh** [xiaohu2015/pvt_detectron2#3]
Hi @xiaohu2015,
Do we have pre-trained models and config files for PVT medium and PVT large?

**Comment by xiaohu2015** [comment]
@trqminh you can modify the config to adpat to PVT medium and PVT large. For the imagenet pretrained models, you can download from the original git repo and convert it to  d2 format.

**Comment by trqminh** [comment]
Thanks @xiaohu2015
